### ISSUE TITLE
Multiple Pretzel API connections - release 1 checklist

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#178]
- [x] for remote datasets with parents, the remote reference axis is added, but the dataset is shown on the local reference axis (if present).
fixed by 86c6f89.
- [x] datasets of initial (primary) endpoint are not shown after changing to another endpoint and coming back.
fixed by 1cb52bc.
- [x] dataset explorer shows 'No datasets found!' although datasets are displayed OK
fixed in 365fbe9.
- [x] /api/dataset/ request going to the ember server port on local instead of the node backend api port
fixed by 9441c43.
- [x] paths request going to local, when some should go to remote server
fixed by 9441c43.
- [x] only request paths for a block adjacency if both blocks are from the same store / endpoint
  initially done in #92, but should be revisited to check functionality.  related : #101 
 done in e7db2b7.
- - [x] could enable joins in frontend for  blocks from different endpoints, using original join / align functionality.
done in 7374a93, 22f1ef0
- [x] axis tracks not displayed
- [x] the endpoints tabs are shown in 'All Datasets' but they apply to all the dataset explorer tabs so they can be placed above the row of tabs 'Genome' 'Genetic Maps' 'All Datasets'
done in 9f67f5d.
- [x] minimise the contents of the 'add new datasource' list.  Probably all that is needed is the + button to add a new one, since they are listed in the tabs, and edit is not needed.
done in 6547ac7.
- [x] when datasource / endpoint is added, connection is done via login; get error, x(probably caused by already being logged in;  perhaps check for existing auth/access token and use that instead of login)
fixed by 743f71a.  (cause was action triggered with empty input values).
- [x] features loaded count in axis title stays at 0 for all loaded datasets, from both local and remote servers
fixed in cd8b788.
- [x] aliases work for the first case attempted (local or remote), after which only datasets from that server will receive aliases, and not for the other; for example, if two blocks loaded from remote which return aliases, remote aliases will work after but not local
- [x] potential timing issue related to blockFeaturesLimits which seems to fail, causes blocks loaded soon after initial log in to not have bounds and as a consequence no ticks or paths loaded
fixed by b088c6e.

- [x] after brush on primary, move brush, features are highlighted but not in count : Avalon_x_Cadenza : 1B : 0 / 1169
done in fd4447f.

- [x] discuss whether namespaces such as '90k' are global or local (if local then reserve a prefix such as PZ: or R: for the namespaces defined by Pretzel main).

- [x] for distinguishing the origin server of the blocks :
. show a coloured border around the server tab in the dataset explorer
  show the same colour in a small block character prefixed to the block name in the axis title 
use a circle

This is part of #75 .
