### ISSUE TITLE
QTL representation

### ISSUE THREAD

**Issue by Don-Isdale** [plantinformatics/pretzel#197]
### Summary
- [x]  the right edge position is not updated in production build

Trait Table
- - [x]    [1-4H/2H] collate the viewed QTLs, grouped by their Trait name, display in View panel below the list of viewed blocks
 14f01a07 : QTL : add Trait table - initially display only.
- - [x] [1-4H/1H] add a toggle on each Trait, to make QTLs of that trait not visible.  ac5abcd2
- - [x] fix issues found in testing
 1f06deb9: handle unexpected data.
 40524447: referenceBlock functions : exclude self and QTLs
 
 - [x] [1-2H/2H] create test data with duplicates for QTL overlap test
 32632624 : QTL data loading : handle additional QTLs within a chr

- - [x] [1-2H/1H] show trait colour in table. b0f81a90
- - - [x] [1H/0.5H] re-connect visible checkbox. 0fdb1131: ( QTL Trait Table )

- [x] [1-2H/2H] QTL data loading : only seeing last QTL of each parent (in Durum_QTL_test.xlsx)
dc7f4b60: spreadsheet / QTL upload : start new Dataset only when change in parentName

- [x] [1H/2H] get svevo 90k marker dataset from dev for local testing
4163e3d2: add blockExport to export Pretzel json

- [x] [1H/1H] only first Trait of block is shown
 7051a29e: QTL Trait Table : show all QTL features of block

- [x] [1-2H/1H] Trait Table : move checkbox from title bar into top of panel, so that it can align with the other checkboxes. 3dab3dfb
- - [x] [/15min]  same with 'Displayed Data'.
 f2fefb68: Displayed Data : move red minus square title bar into top of panel, so that it can align with the other checkboxes.
- - [x] [/0.5H] if <= 1/2 H : make checkbox same size as red minus in 'Displayed Data'.  3dab3dfb

- [x] [1H/1.5H] Trait Table : implement action for checkbox: viewAllFlag.  65824572

- [ ] [2-3H] exception : lastNode
(not seeing this issue currently)

- [ ] [1-2H] either flanking marker or start/end position, use FM if both. use just 1, (no error bar).
started : 821f0b5a : ... valueCompute() : Flanking Markers take precedence, if defined.

QTL data loading :
- [x] [1-2H/1H] handle comma within quoted string (e.g. Citation). ca68d065

- [x] [1H] handle dataset worksheet not having a column in Metadata (datasetMeta)

- [x]  [1-2H] brushing QTL : currently matches only the start. also match the end.
(defer this if the estimate is beyond 2H)
- [ ] [1-2H] Trait Table : visible checkbox : update rectangle widths when #layers change
- [ ] [1H] Trait Table : background colour is highlight for all rows.

---
(from meeting 2021Sep23) :
- [x] [2-3H/2H] remove traits from trait table when (QTL) blocks are un-viewed. 4e8795df (v2.11.1)

---

from testing reported 2021 Oct 14, (e.g. dataset IWGSCv2 : 7D Semagn2021_QTL : 7D )
- [x] [1-2H/2H] erratic transition in QTL with duplicate location
35bbd721 : axis tracks : append featureId to make udescription and trackKeyFn unique.

---

## QTL :
A QTL functionally is like a track; a difference is that it would be shown outside the axis;
using a principle that inside the axis is the base data i.e. features / tracks, and outside is derived / analysis / classification / meta, such as QTLs, and further out : paths.

Questions :
- should paths stop outside the QTL, or pass through it ?
- should QTLs be shown on either side, or only on the right (non-axis) side ?
- QTL can be dragged wider ?

If QTL is shown only on the right and paths stop outside QTL, then a likely implementation would be to simply move the vertical bracked-shaped path which forms the right-hand edge of the axis;  i.e. block layout is the same, just position QTL blocks after the other blocks, and show the edge inside the QTL blocks.

use the concept of parent : QTL parent is a GM
parent funcationality already implemented : explorer, block add,
 axes grouping, brushing, zoom, etc

QTL is delimited by start,end which are either cM or feature name, referring to the centiMorgon position or feature position within the parent GM.

may have multiple QTLs in a dataset; perhaps multiple in a block ?
  currently the granularity of display is the block : when the block is viewed, all tracks in the block are displayed
  so that could guide whether the user places multiple QTLs in one block.

click on QTL :  menu/dialog with actions : select all features in the region

similarly could click on non-QTL tracks : menu / dialog has actions : show a text label beside the feature, outside the axis
These feature labels could be dragged around by the user;  this would assign an <x,y> offset to the label, which would be preserved if the axis is zoomed / moved.

---

##### Related : 

#46 : discussion : projection of multiple QTLs onto a reference; selecting QTLs to align. 
This describes a larger QTL work-flow

#95 
#91 

done: #233 : 756f60e : add QTL import; this is a first pass, will evolve.

**Comment by Don-Isdale** [comment]
notes from discussion Aug31 :

from discussion of the 3 questions :
1. paths should pass under the QTL representation
1. initially show the QTL on the right side, since that fits more easily within existing code
1. fixed width initially


QTL : possibly an I-beam / error-bar instead of a rectangle, but just do the easiest first.

order of priority (J) :
1. QTL -> select features within the QTL region
1. select features or brush axis -> create QTL on fly

- [ ] upload csv - select type - qtl
- -  [ ] ability to input an interval in csv

**Comment by Don-Isdale** [comment]
### Initial Representation.  Data structure.
[discussed data structure options for QTLs : 1 QTL per block, multiple QTLs in a block - can lookup from each displayed feature on map - is it a FM in a viewed QTL, if so display.
 sounds like implementing parent relationship for QTL -> GM matches best with the feature roadmap ]

Some of the main changes required;  will likely add to this list :
- [ ] [2-16H] implement relationship between QTL block and parent GM;  this is the same structure as the relationship between child data blocks on parent physical / reference,
so the same functions and structures will be used, with a few key changes.
- - [ ] [2-4H] lookup the location of QTL's flanking markers from the parent GM;  this is a text -> position lookup, which is the key difference with child data blocks on physical reference, in which the features contain the position / interval.
- - [ ] [2-8H] GMs will continue to display their own data, in addition to the child data blocks.
- [ ] show as triangles with lines - just the outer FMs (later can show LOD curve, which is more informative than the various LOD stats given in spreadsheet)
- - [ ] [1-2H] use block colour initially
- - [ ] [4H] later implement trait colour, which will be global
- initially same offset for all lines/triangles; later :
- - [ ] [8-16H] offset lines/triangles individually to avoid overlap - can factor the existing track layering logic.

ontology : reserved fields in meta with defined meaning,   research ontology trait QTL

### QTL idenfication
ID is : Trait + parentName + Scope (Linkage Group),
 QTL column in the spreadsheet is an optional descriptive name, not identifier
 (e.g. in Lentil example it seems to indicate the parent which is donor of the QTL)
The name displayed for the dataset can be a combination of these, including the latter if it is given.

The Trait could optionally be a standard trait using identifiers from reference ontologies (e.g. https://planteome.org/), e.g. CO_339:0000018 would display as 'Boron toxicity tolerance' with a link to  https://www.cropontology.org/terms/CO_339:0000018/

QTL range - not needed, can get from range of FMmarker positions

**Comment by Don-Isdale** [comment]
(these are rough initial estimates - will refine each as detail is added to the design).

- [ ] [4-12H] display QTLs outside the split axis, on the left side
- [8-16h] The representation would ideally be an empty bracket, rather than the current solid rectangle used for axis tracks.

- loading QTL from spreadsheet :
- - [ ] [8-12H] load flanking markers as Feature.values.flankingMarkers []
- - [ ] [8H] add extra columns and other info

**Comment by Don-Isdale** [comment]
####  Tasks concurrent with this branch

- [ ] [1H] NODE_ENV may default to development; try renaming component-config.{,production.}json
and setting explicitly : export NODE_ENV='production'
(or adding that to backend/.env)

**Comment by Don-Isdale** [comment]
some extra items which may be included in this branch / release :

---

- QTL can be hollow, with trait colour for the border and name text
possibly : with name text shown inside the QTL;  that depends on the length of the QTL in pixels relative to the length of the name text.
---

- some diagrams show error bars around the QTL; this may be used to indicate both :
- - the range of the QTL as determined by the LOD score threshold (solid rectangle), and
- - the position of the nearest flanking markers outside the QTL, as indicated by the error bars
e.g. https://www.frontiersin.org/files/Articles/587553/fgene-11-01012-HTML/image_m/fgene-11-01012-g003.jpg
and https://jcottonres.biomedcentral.com/articles/10.1186/s42397-019-0029-y/figures/1

To support this, we could use QTL Feature.value[start,end] as the QTL position (from LOD score).
Feature.values{ flankingMarkers [] } would still be used to automatically determine the flanking marker extent via lookup in the parent GM;
and would be used to position the error bars.
This is a fairly minor change.  ATM it calculates the flanking marker extent when the features are loaded; this would remain the same;
the change would be to not set .value[start,end] if they already had a value. So that part will be ~1 line of code.  The other part would be :
- - [2-4H] draw an error bar.
If the QTL rectangle is hollow then it should stop at the top & bottom of the rectangle;  if the QTL rectangle is solid then the calculation is simpler - just draw straight through since the colour is the same.
---
- Trait Table
- - [ ] [1H] collate the viewed QTLs, grouped by their Trait name, display in View panel below the list of viewed blocks
- - [ ] [1-2H] add a toggle on each Trait, to make QTLs of that trait not visible.
